### ISSUE TITLE
Dried Spice prevents Ad Astra Rockets from being fueled

### ISSUE THREAD

**Issue by CollapitalDev** [Yirmiri/Dried-Spice#1]
Forge: 47.2.30
Attempting to fuel an Ad Astra rocket via Fuel/Cryo Fuel Buckets fails. The fuel simply is not accepted. Additionally, the pre-fueled rockets that appear in JEI do not have fuel in them. However, a rocket that has been placed and fueled prior to installing Dried Spice remains fueled. This issue does not exist when using just Ad Astra and its dependencies. All four versions of Dried Spice (1.0.0, 1.0.1, 1.0.1.1, and 1.0.1.2) have this issue with Ad Astra 1.15.18. I have tested Dried Spice 1.0.1.2 with Ad Astra 1.15.18, the most recent Beta version, 1.15.17, the previous Beta version, and 1.15.5, the most recent Stable version. All three versions had the same issue.

**Comment by Yirmiri** [comment]
Thank you, a fix for this issue will be included in the next update :)
