### ISSUE TITLE
[NeoForge] Crash with no other mods besides TipsyLib

### ISSUE THREAD

**Issue by Reshirou** [Yirmiri/Dried-Spice#3]
[Here](https://pastebin.com/jm8yQ8X7) is a pastebin of the crash report,
[Here](https://pastebin.com/hvGzx3BM) is a pastebin of the latest log
(I renamed the mod jars for my own organization)

P.S. TipsyLib does not crash by itself. Only Dried Spice crashes.

**Comment by Yirmiri** [comment]
For the time Dried Spice is incompatible with the latest (Neo)Forge version of TipsyLib. As a temporary solution until next Dried Spice update you can use the previous TipsyLib version.
